import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { getMessage } from './api/hello'
import Card from '@/components/Card'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPaperPlane } from '@fortawesome/free-solid-svg-icons'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState({});
  const [loading, setLoading] = useState(false)

  const fetchData = async () => {
    setLoading(true)
    const dataMessage = await getMessage();
    if (dataMessage.data) {
      setLoading(false)
      setData(dataMessage.data)
    }
  }

  useEffect(() => {
    fetchData()
  }, [])

  console.log(data)
  return (
    <>
      <Head>
        <title>Secret Message</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className='container'>
          {loading ? (
            <div className='flex justify-center align-center'>
              <h4>Loading...</h4>
            </div>
          ) : (
            <>
              {data.length === 0 ? (
                <div className="flex justify-center align-center">
                  <p>Belum ada pesan</p>
                </div>
              ) : (
                <div className={`grid ${styles.card_wrapper}`}>
                  <Card data={data} />
                </div>
              )}
              <Link href="/create" className={styles.btn}>Kirim Pesan <FontAwesomeIcon icon={faPaperPlane}/></Link>
            </>
          )}
        </div>
      </main>
    </>
  )
}
